// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwjWM_g6m8g_ruzgkevCRUjZDOD9_UGPY',
    appId: '1:905373761276:web:3a927465b8f97e06496179',
    messagingSenderId: '905373761276',
    projectId: 'connect-call-7b93f',
    authDomain: 'connect-call-7b93f.firebaseapp.com',
    storageBucket: 'connect-call-7b93f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT9dqdaSmvjpH-hIhqX6S6mQnAh5RCiBo',
    appId: '1:905373761276:android:8852318c4663daac496179',
    messagingSenderId: '905373761276',
    projectId: 'connect-call-7b93f',
    storageBucket: 'connect-call-7b93f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7hiwjVU8he7vn-mwhrhA54PIoaz78Zes',
    appId: '1:905373761276:ios:2484485e52f2ca02496179',
    messagingSenderId: '905373761276',
    projectId: 'connect-call-7b93f',
    storageBucket: 'connect-call-7b93f.firebasestorage.app',
    iosBundleId: 'com.example.connectCall',
  );
}
